/**
 * PDF Report Generator for mpx-db
 * 
 * Generates professional database reports using PDFKit.
 * Style consistent with mpx-scan and mpx-api PDF reports.
 */

import PDFDocument from 'pdfkit';
import { createWriteStream, readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const pkg = JSON.parse(readFileSync(join(__dirname, '../../package.json'), 'utf8'));

// Color palette (consistent with mpx-scan / mpx-api)
const COLORS = {
  primary: '#1a56db',
  dark: '#1f2937',
  gray: '#6b7280',
  lightGray: '#e5e7eb',
  white: '#ffffff',
  pass: '#16a34a',
  warn: '#ea580c',
  fail: '#dc2626',
  headerBg: '#1e3a5f',
  sectionBg: '#f3f4f6',
};

/**
 * Check for page overflow and add page if needed
 */
function checkPage(doc, minSpace = 120) {
  if (doc.y > doc.page.height - minSpace) {
    doc.addPage();
    doc.y = 50;
  }
}

/**
 * Draw consistent header bar
 */
function drawHeader(doc, title, subtitle) {
  const pageWidth = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  doc.rect(0, 0, doc.page.width, 100).fill(COLORS.headerBg);
  doc.fontSize(22).fillColor(COLORS.white).font('Helvetica-Bold')
    .text(title, 50, 30);
  doc.fontSize(10).fillColor('#a0b4cc').font('Helvetica')
    .text(subtitle, 50, 60);
  doc.y = 120;
  return pageWidth;
}

/**
 * Draw footers on all pages
 */
function drawFooters(doc, pageWidth) {
  const now = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  });
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    const footerY = doc.page.height - 35;
    doc.fontSize(7).fillColor(COLORS.gray).font('Helvetica')
      .text(
        `Generated by mpx-db v${pkg.version} on ${now}`,
        50, footerY, { width: pageWidth, align: 'center' }
      );
    doc.text(
      `Page ${i + 1} of ${range.count}`,
      50, footerY + 12, { width: pageWidth, align: 'center' }
    );
  }
}

/**
 * Draw a data table
 */
function drawTable(doc, headers, rows, pageWidth, options = {}) {
  const colWidths = options.colWidths || headers.map(() => pageWidth / headers.length);
  const startX = 50;
  
  // Header row
  checkPage(doc, 80);
  let x = startX;
  doc.roundedRect(startX, doc.y, pageWidth, 22, 3).fill(COLORS.primary);
  for (let i = 0; i < headers.length; i++) {
    doc.fontSize(9).fillColor(COLORS.white).font('Helvetica-Bold')
      .text(headers[i], x + 6, doc.y + 5, { width: colWidths[i] - 12 });
    x += colWidths[i];
  }
  doc.y += 26;

  // Data rows
  for (let r = 0; r < rows.length; r++) {
    checkPage(doc, 40);
    const row = rows[r];
    const bg = r % 2 === 0 ? COLORS.sectionBg : COLORS.white;
    
    // Calculate row height
    let maxH = 16;
    for (let i = 0; i < row.length; i++) {
      const h = doc.heightOfString(String(row[i] ?? ''), { width: colWidths[i] - 12, fontSize: 8 });
      if (h + 8 > maxH) maxH = h + 8;
    }

    doc.rect(startX, doc.y, pageWidth, maxH).fill(bg);
    x = startX;
    for (let i = 0; i < row.length; i++) {
      const val = row[i] === null || row[i] === undefined ? '—' : String(row[i]);
      const color = val === '—' ? COLORS.gray : COLORS.dark;
      doc.fontSize(8).fillColor(color).font('Helvetica')
        .text(val, x + 6, doc.y + 4, { width: colWidths[i] - 12 });
      x += colWidths[i];
    }
    doc.y += maxH;
  }
  doc.y += 10;
}

/**
 * Generate schema report PDF
 */
export function generateSchemaPDF(dbInfo, tables, tableSchemas, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      const now = new Date().toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric',
        hour: '2-digit', minute: '2-digit',
      });

      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: `mpx-db Schema Report — ${dbInfo.database || dbInfo.path || 'Database'}`,
          Author: 'mpx-db',
          Subject: 'Database Schema Report',
          Creator: `mpx-db v${pkg.version}`,
        },
        bufferPages: true,
      });

      const stream = createWriteStream(outputPath);
      doc.pipe(stream);

      const dbName = dbInfo.database || dbInfo.path || 'Database';
      const pageWidth = drawHeader(doc,
        'mpx-db Schema Report',
        `v${pkg.version}  •  ${now}  •  ${dbName}`
      );

      // ─── Summary Box ───
      doc.roundedRect(50, doc.y, pageWidth, 80, 6).fill(COLORS.sectionBg);
      const summaryTop = doc.y + 12;

      doc.circle(100, summaryTop + 28, 26).fill(COLORS.primary);
      doc.fontSize(20).fillColor(COLORS.white).font('Helvetica-Bold')
        .text(String(dbInfo.tables), 100 - 20, summaryTop + 16, { width: 40, align: 'center' });

      doc.fontSize(14).fillColor(COLORS.dark).font('Helvetica-Bold')
        .text(`${dbInfo.type} Database`, 145, summaryTop + 5);
      doc.fontSize(10).fillColor(COLORS.gray).font('Helvetica')
        .text(`${dbInfo.tables} tables  •  ${dbInfo.totalRows.toLocaleString()} total rows  •  ${dbInfo.sizeFormatted}`, 145, summaryTop + 25);

      doc.y = summaryTop + 68;

      // ─── Tables Overview ───
      doc.y += 10;
      doc.fontSize(14).fillColor(COLORS.dark).font('Helvetica-Bold')
        .text('Tables', 50, doc.y);
      doc.y += 20;

      const tableRows = tables.map(t => [t.name, t.type, t.rows.toLocaleString()]);
      drawTable(doc, ['Table', 'Type', 'Rows'], tableRows, pageWidth, {
        colWidths: [pageWidth * 0.5, pageWidth * 0.25, pageWidth * 0.25]
      });

      // ─── Table Schemas ───
      for (const { name, columns } of tableSchemas) {
        checkPage(doc, 100);

        doc.y += 5;
        doc.roundedRect(50, doc.y, pageWidth, 26, 4).fill(COLORS.headerBg);
        doc.fontSize(11).fillColor(COLORS.white).font('Helvetica-Bold')
          .text(name, 60, doc.y + 7);
        doc.fontSize(9).fillColor('#a0b4cc').font('Helvetica')
          .text(`${columns.length} columns`, 60, doc.y + 7, { width: pageWidth - 20, align: 'right' });
        doc.y += 32;

        const colRows = columns.map(c => [
          c.name,
          c.type,
          c.nullable ? 'YES' : 'NO',
          c.default || '—',
          c.primaryKey ? 'PRI' : '—'
        ]);

        drawTable(doc, ['Column', 'Type', 'Nullable', 'Default', 'Key'], colRows, pageWidth, {
          colWidths: [pageWidth * 0.28, pageWidth * 0.22, pageWidth * 0.15, pageWidth * 0.2, pageWidth * 0.15]
        });
      }

      drawFooters(doc, pageWidth);
      doc.end();

      stream.on('finish', () => resolve(outputPath));
      stream.on('error', reject);
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Generate query results PDF
 */
export function generateQueryPDF(rows, meta, outputPath) {
  return new Promise((resolve, reject) => {
    try {
      const now = new Date().toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric',
        hour: '2-digit', minute: '2-digit',
      });

      const doc = new PDFDocument({
        size: 'A4',
        layout: rows.length > 0 && Object.keys(rows[0]).length > 5 ? 'landscape' : 'portrait',
        margins: { top: 50, bottom: 50, left: 50, right: 50 },
        info: {
          Title: `mpx-db Query Report`,
          Author: 'mpx-db',
          Subject: 'Database Query Results',
          Creator: `mpx-db v${pkg.version}`,
        },
        bufferPages: true,
      });

      const stream = createWriteStream(outputPath);
      doc.pipe(stream);

      const pageWidth = drawHeader(doc,
        'mpx-db Query Report',
        `v${pkg.version}  •  ${now}`
      );

      // Query info
      doc.roundedRect(50, doc.y, pageWidth, 60, 6).fill(COLORS.sectionBg);
      const summaryTop = doc.y + 10;

      doc.fontSize(9).fillColor(COLORS.gray).font('Helvetica').text('SQL Query:', 60, summaryTop);
      doc.fontSize(9).fillColor(COLORS.dark).font('Helvetica-Bold')
        .text(meta.sql || '—', 60, summaryTop + 14, { width: pageWidth - 20 });
      
      doc.fontSize(9).fillColor(COLORS.gray).font('Helvetica')
        .text(`${rows.length} row(s)  •  ${meta.duration || 0}ms`, 60, summaryTop + 34);

      doc.y = summaryTop + 56;

      if (rows.length === 0) {
        doc.y += 20;
        doc.fontSize(12).fillColor(COLORS.gray).font('Helvetica')
          .text('No rows returned.', 50, doc.y, { width: pageWidth, align: 'center' });
      } else {
        doc.y += 10;
        const columns = Object.keys(rows[0]);
        const colWidth = pageWidth / columns.length;
        const dataRows = rows.map(row => columns.map(c => row[c]));
        drawTable(doc, columns, dataRows, pageWidth, {
          colWidths: columns.map(() => colWidth)
        });
      }

      drawFooters(doc, pageWidth);
      doc.end();

      stream.on('finish', () => resolve(outputPath));
      stream.on('error', reject);
    } catch (err) {
      reject(err);
    }
  });
}
